apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gitaly
spec:
  capacity: 
    storage: 50Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /data/vol-gitaly
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgre
spec:
  capacity: 
    storage: 8Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /data/vol-gitaly
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio
spec:
  capacity: 
    storage: 10Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /data/vol-minio
    type: DirectoryOrCreate

---    
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis
spec:
  capacity: 
    storage: 5Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /data/vol-gitaly
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
spec:
  capacity: 
    storage: 8Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /data/vol-prometheus
    type: DirectoryOrCreate
